In [1]:
import pandas as pd
import requests
import sqlite3

#Alerta de verificação da API

def api_request(url, headers):
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Erro ao acessar a API")
        return None


# Definindo url e cabeçalho da API
    
url_genero = "https://api.themoviedb.org/3/genre/movie/list?language=pt"
headers_genero = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNDY5ZmZlMzViYTg1MzYwMmRmN2Q1NzkxMDk0ZjczOCIsInN1YiI6IjY1NzI1MmRiNGIwYzYzMDEwMDhlNjBlMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.RNrfhZHiG5mHkfPjf--EhYs4-l8tDUy48oKiAPy2qYY"
}

url_filmes = "https://api.themoviedb.org/3/movie/popular?language=pt-BR&page=3"
headers_filmes = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNDY5ZmZlMzViYTg1MzYwMmRmN2Q1NzkxMDk0ZjczOCIsInN1YiI6IjY1NzI1MmRiNGIwYzYzMDEwMDhlNjBlMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.RNrfhZHiG5mHkfPjf--EhYs4-l8tDUy48oKiAPy2qYY"
}

url_series = "https://api.themoviedb.org/3/tv/popular?language=en-US&page=1"
headers_series = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNDY5ZmZlMzViYTg1MzYwMmRmN2Q1NzkxMDk0ZjczOCIsInN1YiI6IjY1NzI1MmRiNGIwYzYzMDEwMDhlNjBlMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.RNrfhZHiG5mHkfPjf--EhYs4-l8tDUy48oKiAPy2qYY"
}

# Chamando a função:
response_genero = api_request(url_genero, headers_genero)
response_filmes = api_request(url_filmes, headers_filmes)
response_series = api_request(url_series, headers_series)

In [2]:
# Utilizando a função json_normalize para apresentar os resultados em forme de tabela
# E o metodo fillna para tratativa de valores ausentes
genero_full = pd.DataFrame(response_genero)
genero_full = pd.json_normalize(genero_full.genres).fillna(0)
genero_full

       id               name
0      28               Ação
1      12           Aventura
2      16           Animação
3      35            Comédia
4      80              Crime
5      99       Documentário
6      18              Drama
7   10751            Família
8      14           Fantasia
9      36           História
10     27             Terror
11  10402             Música
12   9648           Mistério
13  10749            Romance
14    878  Ficção científica
15  10770          Cinema TV
16     53           Thriller
17  10752             Guerra
18     37           Faroeste

In [3]:
# Utilizando a função json_normalize para apresentar os resultados em forme de tabela
# drop para excluir colunas que não serão utilizadas
# E o metodo fillna para tratativa de valores ausentes
filmes_full = pd.DataFrame(response_filmes)
filmes_full = pd.json_normalize(filmes_full.results).fillna(0)
filmes_full['genre_ids'] = filmes_full['genre_ids'].apply(lambda x: x[0] if x else None)

excluir_col_filmes = ['adult','backdrop_path','original_title','original_language','popularity','poster_path','release_date','video','vote_count']

filmes_full = filmes_full.drop(excluir_col_filmes, axis=1)


filmes_full

,genre_ids,id,overview,title,vote_average
0,28,899445,Navegando sozinha pelo Caribe num barco a vela...,Terror nas Profundezas,4.924
1,28,667538,"Nesta aventura cheia de adrenalina, Optimus Pr...",Transformers: O Despertar das Feras,7.394
2,16,569094,Miles Morales retorna para o próximo capítulo ...,Homem-Aranha: Através do Aranhaverso,8.400
3,28,603692,"Com o preço por sua cabeça cada vez maior, Joh...",John Wick 4: Baba Yaga,7.765
4,18,1010581,"Noah é obrigada a mudar de cidade, deixando se...",Minha Culpa,8.052
5,53,844416,"Na paisagem sombria do Delta do Mississippi, u...",Rumble Through the Dark,6.591
6,27,968051,Quatro anos após os acontecimentos na abadia d...,A Freira 2,6.900
7,35,772,"Garoto se vê novamente sozinho, quando em virt...",Esqueceram de Mim 2: Perdido em Nova York,6.727
8,16,1022796,"No reino mágico de Rosas, Asha é uma moça pers...",Wish: O Poder dos Desejos,6.358
9,27,951491,Entre os eventos de “Jogos Mortais” e “Jogos M...,Jogos Mortais X,7.370
10,27,1008042,Quando um grupo de amigos descobre como conjur...,Fale Comigo,7.200
11,878,934194,,Slash/Back,6.563
12,12,315162,O Gato de Botas descobre que sua paixão pela a...,Gato de Botas 2: O Último Pedido,8.253
13,27,1161048,Durante um evento que aparentava ser inofensiv...,Conferência Mortal,5.370
14,28,615656,Um mergulho exploratório nas profundezas do oc...,Megatubarão 2,6.674
15,28,975902,Boudica governa o povo Iceniano com seu marido...,Boudica,6.000
16,28,575264,Ethan Hunt e sua equipe embarcam em sua missão...,Missão: Impossível - Acerto de Contas Parte 1,7.577
17,28,755401,,Skydog,6.583
18,878,609681,Quando suas obrigações a levam a uma fenda esp...,As Marvels,6.434
19,16,893723,"Um meteoro mágico cai em Adventure City, dá su...",Patrulha Canina: Um Filme Superpoderoso,7.012

In [4]:
# Utilizando a função json_normalize para apresentar os resultados em forme de tabela
# drop para excluir colunas que não serão utilizadas
# E o metodo fillna para tratativa de valores ausentes
series_full = pd.DataFrame(response_series)
series_full = pd.json_normalize(series_full.results).fillna(0)
series_full['genre_ids'] = series_full['genre_ids'].apply(lambda x: x[0] if x else None)
series_full['origin_country'] = series_full['origin_country'].apply(lambda x: x[0] if x else None)

excluir_col_series = ['adult','backdrop_path','original_name','original_language','popularity','poster_path','first_air_date','vote_count']

series_full = series_full.drop(excluir_col_series, axis=1)

series_full

,genre_ids,id,origin_country,overview,name,vote_average
0,10766,206559,ZA,A South African Afrikaans soap opera. It is se...,Binnelanders,5.978
1,10767,61818,US,"Seth Meyers, who is ""Saturday Night Live’s"" lo...",Late Night with Seth Meyers,5.500
2,80,72879,FR,"The story revolves around the people of Sète, ...",Tomorrow Is Ours,6.245
3,80,4614,US,From murder and espionage to terrorism and sto...,NCIS,7.616
4,37,10980,US,Have Gun – Will Travel is an American Western ...,"Have Gun, Will Travel",7.500
5,18,39351,US,After Portland homicide detective Nick Burkhar...,Grimm,8.285
6,16,60625,US,Rick is a mentally-unbalanced but scientifical...,Rick and Morty,8.699
7,10759,57041,JP,In an era where aliens have invaded and taken ...,Gintama,8.000
8,35,66465,IN,,The Kapil Sharma Show,7.483
9,10759,108978,US,"Jack Reacher, a veteran military police invest...",Reacher,8.080
10,10767,60694,US,A half-hour satirical look at the week in news...,Last Week Tonight with John Oliver,7.896
11,10759,62643,US,When heroes alone are not enough ... the world...,DC's Legends of Tomorrow,7.324
12,35,63770,US,Stephen Colbert brings his signature satire an...,The Late Show with Stephen Colbert,6.523
13,18,13897,US,Ben Casey is an American medical drama series ...,Ben Casey,5.692
14,10759,17610,US,The exploits of the Los Angeles–based Office o...,NCIS: Los Angeles,7.567
15,18,2625,US,"Dr. Mark Sloan is a good-natured, offbeat phys...",Diagnosis: Murder,7.074
16,18,14944,US,Robert Montgomery Presents is an American dram...,Robert Montgomery Presents,5.000
17,10766,81329,FR,,Chronicles of the Sun,7.621
18,18,46952,US,"Raymond ""Red"" Reddington, one of the FBI's mos...",The Blacklist,7.620
19,18,32692,US,A drama about a multi-generational family of c...,Blue Bloods,7.800

In [5]:
# Renomeando o titulo das colunas
genero_full = genero_full.rename(columns={
    'id': 'id_genero',
    'name': 'genero'
})
filmes_full = filmes_full.rename(columns={				
    'genre_ids': 'id_genero',
    'id': 'id_filme',
    'original_title': 'titulo_original',
    'overview': 'overview',
    'title':'titulo',
    'vote_average':'votacao_media'
})

series_full = series_full.rename(columns={
    'genre_ids': 'id_genero',
    'id': 'id_serie',
    'origin_country': 'pais_origem',
    'overview': 'overview',
    'name':'titulo',
    'vote_average':'votacao_media'
})

In [6]:
# Relacionando as tabelas

join_generos = pd.merge(pd.merge(genero_full,filmes_full, on='id_genero', how='left'),series_full, on='id_genero', how='left') 


join_generos.rename(columns={'titulo_x': 'titulo'}, inplace=True)

join_generos['Categoria'] = join_generos.apply(lambda row: 'Filme' if pd.notna(row['id_filme']) else 'Serie', axis=1)

join_generos['titulo'] = join_generos['titulo'].fillna(join_generos['titulo_y'])

join_generos = join_generos.dropna(subset=['titulo','titulo_y'], how='all')

join_generos.drop(['id_genero','id_filme','overview_x','votacao_media_x','id_serie','pais_origem','overview_y','titulo_y','votacao_media_y'], axis=1, inplace=True)



join_generos

               genero                                         titulo Categoria
0                Ação                         Terror nas Profundezas     Filme
1                Ação            Transformers: O Despertar das Feras     Filme
2                Ação                         John Wick 4: Baba Yaga     Filme
3                Ação                                  Megatubarão 2     Filme
4                Ação                                        Boudica     Filme
5                Ação  Missão: Impossível - Acerto de Contas Parte 1     Filme
6                Ação                                         Skydog     Filme
7            Aventura               Gato de Botas 2: O Último Pedido     Filme
8            Animação           Homem-Aranha: Através do Aranhaverso     Filme
9            Animação                      Wish: O Poder dos Desejos     Filme
10           Animação        Patrulha Canina: Um Filme Superpoderoso     Filme
11            Comédia      Esqueceram de Mim 2: Perdido em Nova York     Filme
12            Comédia      Esqueceram de Mim 2: Perdido em Nova York     Filme
13              Crime                               Tomorrow Is Ours     Serie
14              Crime                                           NCIS     Serie
16              Drama                                    Minha Culpa     Filme
17              Drama                                    Minha Culpa     Filme
18              Drama                                    Minha Culpa     Filme
19              Drama                                    Minha Culpa     Filme
20              Drama                                    Minha Culpa     Filme
21              Drama                                    Minha Culpa     Filme
25             Terror                                     A Freira 2     Filme
26             Terror                                Jogos Mortais X     Filme
27             Terror                                    Fale Comigo     Filme
28             Terror                             Conferência Mortal     Filme
32  Ficção científica                                     Slash/Back     Filme
33  Ficção científica                                     As Marvels     Filme
35           Thriller                        Rumble Through the Dark     Filme
37           Faroeste                          Have Gun, Will Travel     Serie

In [7]:
# Tratando os tipos das variaveis
genero_full['id_genero'] = genero_full['id_genero'].astype('int')
genero_full['genero'] = genero_full['genero'].astype('string')
					
filmes_full['id_genero'] = filmes_full['id_genero'].astype('int')
filmes_full['id'] = filmes_full['id_filme'].astype('int')
filmes_full['overview'] = filmes_full['overview'].astype('string')
filmes_full['titulo'] = filmes_full['titulo'].astype('string')
filmes_full['votacao_media'] = filmes_full['votacao_media'].astype('float')

series_full['genre_ids'] = series_full['id_genero'].astype('int')
series_full['id'] = series_full['id_serie'].astype('int')
series_full['origin_country'] = series_full['pais_origem'].astype('string')
series_full['overview'] = series_full['overview'].astype('string')
series_full['titulo'] = series_full['titulo'].astype('string')
series_full['votacao_media'] = series_full['votacao_media'].astype('float')

In [8]:
#Visualizando tipagem dos dados:

genero_full.dtypes

id_genero             int32
genero       string[python]
dtype: object

In [9]:
#Visualizando tipagem dos dados:

filmes_full.dtypes

id_genero                 int32
id_filme                  int64
overview         string[python]
titulo           string[python]
votacao_media           float64
id                        int32
dtype: object

In [10]:
#Visualizando tipagem dos dados:

genero_full.dtypes

id_genero             int32
genero       string[python]
dtype: object

In [11]:
# Visualizando dados após tratativas:
genero_full

    id_genero             genero
0          28               Ação
1          12           Aventura
2          16           Animação
3          35            Comédia
4          80              Crime
5          99       Documentário
6          18              Drama
7       10751            Família
8          14           Fantasia
9          36           História
10         27             Terror
11      10402             Música
12       9648           Mistério
13      10749            Romance
14        878  Ficção científica
15      10770          Cinema TV
16         53           Thriller
17      10752             Guerra
18         37           Faroeste

In [12]:
# Visualizando dados após tratativas:
filmes_full

,id_genero,id_filme,overview,titulo,votacao_media,id
0,28,899445,Navegando sozinha pelo Caribe num barco a vela...,Terror nas Profundezas,4.924,899445
1,28,667538,"Nesta aventura cheia de adrenalina, Optimus Pr...",Transformers: O Despertar das Feras,7.394,667538
2,16,569094,Miles Morales retorna para o próximo capítulo ...,Homem-Aranha: Através do Aranhaverso,8.400,569094
3,28,603692,"Com o preço por sua cabeça cada vez maior, Joh...",John Wick 4: Baba Yaga,7.765,603692
4,18,1010581,"Noah é obrigada a mudar de cidade, deixando se...",Minha Culpa,8.052,1010581
5,53,844416,"Na paisagem sombria do Delta do Mississippi, u...",Rumble Through the Dark,6.591,844416
6,27,968051,Quatro anos após os acontecimentos na abadia d...,A Freira 2,6.900,968051
7,35,772,"Garoto se vê novamente sozinho, quando em virt...",Esqueceram de Mim 2: Perdido em Nova York,6.727,772
8,16,1022796,"No reino mágico de Rosas, Asha é uma moça pers...",Wish: O Poder dos Desejos,6.358,1022796
9,27,951491,Entre os eventos de “Jogos Mortais” e “Jogos M...,Jogos Mortais X,7.370,951491
10,27,1008042,Quando um grupo de amigos descobre como conjur...,Fale Comigo,7.200,1008042
11,878,934194,,Slash/Back,6.563,934194
12,12,315162,O Gato de Botas descobre que sua paixão pela a...,Gato de Botas 2: O Último Pedido,8.253,315162
13,27,1161048,Durante um evento que aparentava ser inofensiv...,Conferência Mortal,5.370,1161048
14,28,615656,Um mergulho exploratório nas profundezas do oc...,Megatubarão 2,6.674,615656
15,28,975902,Boudica governa o povo Iceniano com seu marido...,Boudica,6.000,975902
16,28,575264,Ethan Hunt e sua equipe embarcam em sua missão...,Missão: Impossível - Acerto de Contas Parte 1,7.577,575264
17,28,755401,,Skydog,6.583,755401
18,878,609681,Quando suas obrigações a levam a uma fenda esp...,As Marvels,6.434,609681
19,16,893723,"Um meteoro mágico cai em Adventure City, dá su...",Patrulha Canina: Um Filme Superpoderoso,7.012,893723

In [13]:
# Visualizando dados após tratativas:

series_full

,id_genero,id_serie,pais_origem,overview,titulo,votacao_media,genre_ids,id,origin_country
0,10766,206559,ZA,A South African Afrikaans soap opera. It is se...,Binnelanders,5.978,10766,206559,ZA
1,10767,61818,US,"Seth Meyers, who is ""Saturday Night Live’s"" lo...",Late Night with Seth Meyers,5.500,10767,61818,US
2,80,72879,FR,"The story revolves around the people of Sète, ...",Tomorrow Is Ours,6.245,80,72879,FR
3,80,4614,US,From murder and espionage to terrorism and sto...,NCIS,7.616,80,4614,US
4,37,10980,US,Have Gun – Will Travel is an American Western ...,"Have Gun, Will Travel",7.500,37,10980,US
5,18,39351,US,After Portland homicide detective Nick Burkhar...,Grimm,8.285,18,39351,US
6,16,60625,US,Rick is a mentally-unbalanced but scientifical...,Rick and Morty,8.699,16,60625,US
7,10759,57041,JP,In an era where aliens have invaded and taken ...,Gintama,8.000,10759,57041,JP
8,35,66465,IN,,The Kapil Sharma Show,7.483,35,66465,IN
9,10759,108978,US,"Jack Reacher, a veteran military police invest...",Reacher,8.080,10759,108978,US
10,10767,60694,US,A half-hour satirical look at the week in news...,Last Week Tonight with John Oliver,7.896,10767,60694,US
11,10759,62643,US,When heroes alone are not enough ... the world...,DC's Legends of Tomorrow,7.324,10759,62643,US
12,35,63770,US,Stephen Colbert brings his signature satire an...,The Late Show with Stephen Colbert,6.523,35,63770,US
13,18,13897,US,Ben Casey is an American medical drama series ...,Ben Casey,5.692,18,13897,US
14,10759,17610,US,The exploits of the Los Angeles–based Office o...,NCIS: Los Angeles,7.567,10759,17610,US
15,18,2625,US,"Dr. Mark Sloan is a good-natured, offbeat phys...",Diagnosis: Murder,7.074,18,2625,US
16,18,14944,US,Robert Montgomery Presents is an American dram...,Robert Montgomery Presents,5.000,18,14944,US
17,10766,81329,FR,,Chronicles of the Sun,7.621,10766,81329,FR
18,18,46952,US,"Raymond ""Red"" Reddington, one of the FBI's mos...",The Blacklist,7.620,18,46952,US
19,18,32692,US,A drama about a multi-generational family of c...,Blue Bloods,7.800,18,32692,US

In [14]:
join_generos

               genero                                         titulo Categoria
0                Ação                         Terror nas Profundezas     Filme
1                Ação            Transformers: O Despertar das Feras     Filme
2                Ação                         John Wick 4: Baba Yaga     Filme
3                Ação                                  Megatubarão 2     Filme
4                Ação                                        Boudica     Filme
5                Ação  Missão: Impossível - Acerto de Contas Parte 1     Filme
6                Ação                                         Skydog     Filme
7            Aventura               Gato de Botas 2: O Último Pedido     Filme
8            Animação           Homem-Aranha: Através do Aranhaverso     Filme
9            Animação                      Wish: O Poder dos Desejos     Filme
10           Animação        Patrulha Canina: Um Filme Superpoderoso     Filme
11            Comédia      Esqueceram de Mim 2: Perdido em Nova York     Filme
12            Comédia      Esqueceram de Mim 2: Perdido em Nova York     Filme
13              Crime                               Tomorrow Is Ours     Serie
14              Crime                                           NCIS     Serie
16              Drama                                    Minha Culpa     Filme
17              Drama                                    Minha Culpa     Filme
18              Drama                                    Minha Culpa     Filme
19              Drama                                    Minha Culpa     Filme
20              Drama                                    Minha Culpa     Filme
21              Drama                                    Minha Culpa     Filme
25             Terror                                     A Freira 2     Filme
26             Terror                                Jogos Mortais X     Filme
27             Terror                                    Fale Comigo     Filme
28             Terror                             Conferência Mortal     Filme
32  Ficção científica                                     Slash/Back     Filme
33  Ficção científica                                     As Marvels     Filme
35           Thriller                        Rumble Through the Dark     Filme
37           Faroeste                          Have Gun, Will Travel     Serie

In [15]:
# Criando conexão com BD
conn = sqlite3.connect('movie.db')

In [16]:
# Salvando DataFrame no BD

genero_full.to_sql('genero', conn,if_exists='replace', index=False)
filmes_full.to_sql('filme', conn,if_exists='replace',index=False)
series_full.to_sql('series', conn,if_exists='replace',index=False)
join_generos.to_sql('join_exemplo', conn,if_exists='replace',index=False)

29